name: generate_apk

   steps:

      
    - name : set up JDK
      uses: actions/setup-java@v2
      with:
        distribution : 'adopt'
        java-version: 11
        cache : 'gradle'
          
    - name: build
      run: ./gradlew assemble

on:

  push:
    branches: [ develop ]

jobs:
  build:
   name : extract_apk
   runs-on: ubuntu-latest
   steps:
    - name : checkout
      uses: actions/checkout@v2
      
    - name : set up JDK
      uses: actions/setup-java@v2
      with:
        distribution : 'adopt'
        java-version: 11
        cache : 'gradle'
          
    - name: build APK
      run: ./gradlew assembleDebug --stacktrace

    - name : Upload Slack
      uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
          file_name: 'meeron.apk'
          file_type: 'apk'
          initial_comment: '${{ github.ref }} 슬랙 배포 성공'
        
    - name: 테스트용 apk artifact 업로드
      uses: actions/upload-artifact@v2
      with:
        name: meeron.apk
        path: app/build/outputs/apk/release/meeron.apk

