name: generate_apk

on:

  push:
    branches: [ develop ,hotfix/* ]

jobs:
  build:
    name: APK Send to Slack
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: key
        run: keytool -exportcert -alias release -keystore key/keystore.jks | openssl sha1 -binary | openssl base64

      - name: build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload Slack
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'app/build/outputs/apk/release/app.apk'
          file_name: 'app.apk'
          file_type: 'apk'
          initial_comment: '${{ github.ref }} 슬랙 배포 성공'

      - name: apk 업로드
        uses: actions/upload-artifact@v2
        with:
          name: meeron.apk
          path: app/build/outputs/apk/release/app.apk

