name: generate_apk

on:

  push:
    branches: [ action_test ]

jobs:
  build:
    name : APK Send to Slack
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'gradle'

    - name: key
      run: keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64

    - name: build APK
      run: ./gradlew assembleDebug --stacktrace

     #    - name : Upload Slack
     #      uses : MeilCli/slack-upload-file@v1
     #      with:
     #          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
     #          channels: ${{ secrets.SLACK_CHANNEL_ID }}
     #          file_path: 'app/build/outputs/apk/debug/app-debug.apk'
     #          file_name: 'app-debug.apk'
     #          file_type: 'apk'
     #          initial_comment: '${{ github.ref }} 슬랙 배포 성공'

     - name: apk 업로드
       uses: actions/upload-artifact@v2
       with:
         name: meeron.apk
         path: app/build/outputs/apk/debug/app-debug.apk

