name: slack_alarm

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
